---
- hosts: all
  become: true
  tasks: 
   - name: installing packages
     yum:
      name: httpd
      state: installed
     when: ansible_os_family == "RedHat"

   - name: start the httpd service
     service:
      name: httpd
      state: started
     when: ansible_os_family == "RedHat"

   - name: install service for debian family
     apt:
      name: apache2
      state: present
     when: ansible_os_family == "Debian"

   - name: start tha apache service
     service:
      name: apache2
      state: started
     when: ansible_os_family == "Debain"

