---
- hosts: all
  tasks: 
   - name: stop current running container
     command: docker stop simple-container 
     ignore_errors: yes
   - name: remove stopped containers
     command: docker rm simple-container
     ignore_errors: yes
   - name: remove docker images
     command: docker rmi simple-image
     ignore_errors: yes
   - name: build docker image using war file
     command: docker build -t simple-image .
     args:
      chdir: /opt/docker 
   - name: create container using above created image
     command: docker run -d --name simple-container -p 8080:8080 simple-image
